### ISSUE TITLE
-Wsequence-point warnings during build

### ISSUE THREAD

**Issue by sanjayankur31** [neuronsimulator/iv#13]
While building iv for NeuroFedora with -Wall etc compiler flags, we caught this in the build logs:

```
g++ -DHAVE_CONFIG_H -I. -I. -Div2_6_compatible -I../../include/IV-2_6 -I../../include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c -o idarrows.o idarrows.cpp
idarrows.cpp: In member function 'virtual void ArrowOpenBSpline::draw(ivCanvas*, ivGraphic*)':
idarrows.cpp:514:52: warning: operation on '*(((ArrowOpenBSpline*)this)->ArrowOpenBSpline::<anonymous>.ivSFH_OpenBSpline::<anonymous>.ivSF_OpenBSpline::<anonymous>.ivOpenBSpline::<anonymous>.ivVertices::_y + ((sizetype)(((long unsigned int)k) * 4)))' may be undefined [-Wsequence-point]
  514 |         _x[l] = _x[k] = _x[j] = tx1; _y[l] = _y[k] = _y[k] = ty1;
      |                                              ~~~~~~^~~~~~~~~~~~~
```

The gcc man page suggests this code may have undefined semantics.
Should the second statement maybe be:

```
 _y[l] = _y[k] = _y[j] = ty1;
```

**Comment by sanjayankur31** [comment]
[build-log.txt](https://github.com/neuronsimulator/iv/files/3856035/build-log.txt)

**Comment by nrnhines** [comment]
Thanks. That does seem to be a typo/bug. I don't notice a difference in arrow  head directions
when changing the second _y[k] to _y[k] but it seems a reasonable change and I will commit it.
For iv, I do experience a considerable number of warnings with the configuration
```
./configure --prefix=`pwd` CC=gcc-8 CXX=g++-8 CFLAGS='-Wall -g -O2' CXXFLAGS='-Wall -g -O2'
```
of the types
unused variable
value computed is not used
... may be used uninitialized
comparison of integer expressions of different signedness
array subscript has type ‘char’
dereferencing type-punned pointer will break strict-aliasing rules

and will deal with them in the future when I have time.

**Comment by nrnhines** [comment]
6af0a60 fixes the idarrows.cpp:514 warning

**Comment by sanjayankur31** [comment]
Thanks! I'll see if I can help fix the other compiler warnings too.
